server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://192.168.1.249:3306/zcps?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&serverTimezone=Asia/Shanghai
    username: ZCPS
    password: ZCPS
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 121.5.177.166
    port: 6379
    password: 14yhl9t
    database: 6
    timeout: 5000
    lettuce:
      pool:
        max-active: 30
        max-wait: -1
        max-idle: 8
        min-idle: 1
  phone:
    num: 18612138266
